spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://0.0.0.0:8080/realms/labs
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs




server:
  port: 8081